version: '3'

services:
  mongo:
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    container_name: "edx.devstack.mongo"
    hostname: mongo.devstack.edx
    image: mongo:${MONGO_VERSION:-3.6.17}
    logging:
      driver: none
    networks:
      default:
        aliases:
          - edx.devstack.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  edxapp:
    # command: bash -c 'source /edx/app/edxapp/venvs/edxapp/bin/activate && paver test_system -s cms --disable_capture'
    # command: bash -c 'source /edx/app/edxapp/venvs/edxapp/bin/activate && pytest $TEST_SYSTEM --splits 3 --group $SHARD'
    #command: bash -c 'source /edx/app/edxapp/venvs/edxapp/bin/activate && pytest $TEST_SYSTEM --splits $SPLITS --group $SHARD'
    command: bash -c 'source /edx/app/edxapp/venvs/edxapp/bin/activate && pytest cms'
    image: ghcr.io/mzulqarnain1/edxapp:testing
    environment:
      TEST_SYSTEM: ${TEST_SYSTEM:-lms}
      SHARD: ${SHARD:-1}
      SPLITS: ${SPLITS:-2}
      EDXAPP_TEST_MONGO_HOST: edx.devstack.mongo
      NO_PYTHON_UNINSTALL: 1
    depends_on:
      - mongo

volumes:
  mongo_data:
