#name: CI
#
#on:
#  pull_request:
#  push:
#    branches:
#      - master
#
#jobs:
#  build_and_publish:
#    name: Setup Test Infrastructure
#    runs-on: ubuntu-20.04
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Create Docker Image
#      run: |
#        docker build -t edxapp_test -f Test.Dockerfile .
#        docker tag edxapp_test ghcr.io/mzulqarnain1/edxapp:${GITHUB_SHA}
#
#    - name: Upload Docker Image
#      run: |
#        echo ${{ secrets.CR_PASSWORD }} | docker login ghcr.io -u mzulqarnain1 --password-stdin
#        docker push ghcr.io/mzulqarnain1/edxapp:${GITHUB_SHA}
#
#  run-tests:
#    name: Unit Tests
#    needs: build_and_publish
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        test-system: [ lms, cms, common, openedx ]
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Download Docker Image
#      run: |
#        echo ${{ secrets.CR_PASSWORD }} | docker login ghcr.io -u mzulqarnain1 --password-stdin
#        docker pull ghcr.io/mzulqarnain1/edxapp:${GITHUB_SHA}
#
#    - name: Run Tests Docker Image
#      env:
#        GITHUB_SHA: ${GITHUB_SHA}
#        TEST_SYSTEM: ${{ matrix.test-system }}
#      run: |
#        docker images
#        make docker_build_test
